# -*- coding: utf-8 -*-
"""Proyek Predictive Analysis Suyanti.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OCkHaZ3tVcqcJp0UWF_Z6sXDzfgB2U7G

# **Proyek Predictive Analysis: Maternal Health - Menilai Resiko Kehamilan**


- **Nama:** Suyanti Witono
- **Email:** suyanti.witono@bpkpenaburjakarta.or.id
- **ID Dicoding:** suyanti_witono_tfde

## **Latar Belakang**
Kehamilan adalah hal yang membahagiakan bagi wanita pada khususnya dan bagi keluarga pada umumnya. Akan tetapi, kehamilan juga perlu diperhatikan karena mengandung resiko.

> Jumlah kematian ibu yang dihimpun dari pencatatan program kesehatan keluarga di Kementerian Kesehatan pada tahun 2020 menunjukkan 4.627 kematian di Indonesia. Jumlah ini menunjukkan peningkatan dibandingkan tahun 2019 sebesar 4.221 kematian. Berdasarkan penyebab, sebagian besar kematian ibu pada tahun 2020 disebabkan oleh perdarahan sebanyak 1.330 kasus, hipertensi dalam kehamilan sebanyak 1.110 kasus, dan gangguan sistem peredaran darah sebanyak 230 kasus. (Kemenkes, 2021)

Usia menjadi salah satu penyebab resiko. Kehamilan pada usia di bawah 17 tahun mengandung resiko karena organ reproduksi belum berkembang sempurna. Seringkali pula, wanita di bawah umur ini tidak mencari pertolongan medis selama kehamilan sampai pada saat melahirkan. Kehamilan di usia tua juga beresiko, terutama di atas usia 35 tahun karena meningkatnya komplikasi dan peluang keguguran (Gloria, 2022).  Selain usia, faktor lain seperti tekanan darah (blood pressure), kadar gula dalam darah (blood sugar level), dan gaya hidup juga mempengaruhi resiko kehamilan (Pawestri, 2023).

Demam selama hamil terutama pada trimester pertama dapat menyebabkan masalah pada perkembangan janin (Karnesyia, 2024). Selain itu, kondisi preeklampsia juga dapat menyebabkan kondisi darurat pada ibu hamil dan janin yang dikandung. Preeklampsia diikuti dengan tekanan darah tinggi, adanya protein pada urine, serta dapat memburuk menjadi serangan jantung atau gagal ginjal akut. Karena itu, usia, tekanan darah, dan kadar gula darah penting untuk dipantau.

Predictive analysis ini akan berfokus pada pengolahan data usia, tekanan darah sistol, tekanan darah diastol, kadar gula darah, suhu tubuh, dan detak jantung untuk menentukan tingkat resiko kehamilan. Dataset yang digunakan adalah https://www.kaggle.com/datasets/csafrit2/maternal-health-risk-data



### **Referensi**
1. Gloria, N. (18 Maret 2022). *9 Faktor Kehamilan Resiko Tinggi, Beserta Penanganannya*. Viva. https://www.viva.co.id/gaya-hidup/kesehatan-intim/1458611-kehamilan-risiko-tinggi
2. Karnesyia, A. (2 Feb 2024). *13 Tanda Kehamilan Beresiko Tinggi dan Penyebab yang Perlu Bunda Tahu*. HaiBunda. https://www.haibunda.com/kehamilan/20240131135720-49-327790/13-tanda-kehamilan-berisiko-tinggi-dan-penyebab-yang-perlu-bunda-tahu
3. Kementerian Kesehatan Republik Indonesia. 2021. *Profil Kesehatan Indonesia 2020*. https://r.search.yahoo.com/_ylt=AwrKCdroQgNnt6kMfDPLQwx.;_ylu=Y29sbwNzZzMEcG9zAzIEdnRpZAMEc2VjA3Ny/RV=2/RE=1728295784/RO=10/RU=https%3a%2f%2fkemkes.go.id%2fapp_asset%2ffile_content_download%2fProfil-Kesehatan-Indonesia-2020.pdf/RK=2/RS=GY0YoJ2jFSy6ggsJBxiuOEndidg-
4. Pawestri, H. S. (25 Jan 2023). *Penyebab Kehamilan Resiko Tinggi dan Cara Menjalaninya*. HelloSehat. https://hellosehat.com/kehamilan/kandungan/masalah-kehamilan/apa-itu-kehamilan-risiko-tinggi/

## **Business Understanding**

### *Problem Statements:*
1. Bagaimana hubungan antara usia, tekanan darah, gula darah, suhu tubuh, dan detak jantung ibu terhadap resiko kehamilan?
2. Berapa tingkat resiko kehamilan dengan parameter tertentu dari kesehatan ibu?

### *Goals:*
1. Mengetahui korelasi antara usia, tekanan darah, gula darah, suhu tubuh, dan detak jantung terhadap resiko kehamilan.
2. Membuat model machine learning yang dapat memprediksi resiko kehamilan berdasarkan parameter tertentu dari kesehatan ibu.

### *Solution Statements:*
Outcomes yang diharapkan adalah 3 kategori: high risk, mid risk, low risk.
Model machine learning akan dibangun dengan beberapa algoritma dan dipilih model dengan kesalahan prediksi terkecil.
1. Multinominal logistic regression.
2. K-Nearest Neighbor.
3. Random Forest.
4. Decision Tree Classifier.

### *Metrik Evaluasi*
Metrik yang digunakan adalah Mean Squared Error (menghitung jumlah selisih kuadrat rata-rata nilai sebenarnya dengan nilai prediksi).

## **Data Understanding**
Data yang digunakan berasal dari Kaggle: Maternal Health Risk Data https://www.kaggle.com/datasets/csafrit2/maternal-health-risk-data
Dataset terdiri dari 1014 data kesehatan ibu hamil dengan parameter kesehatan yaitu usia, tekanan darah sistol, tekanan darah diastol, kadar gula darah, suhu tubuh, dan detak jantung. Tingkat resiko (high risk, mid risk, low risk) adalah fitur target.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

!kaggle datasets download -d csafrit2/maternal-health-risk-data
!unzip maternal-health-risk-data.zip

data = pd.read_csv("/content/Maternal Health Risk Data Set.csv")
data.head()

"""- Age: Usia saat wanita mengandung (dalam satuan tahun).
- SystolicBP: Nilai atas dari tekanan darah (dalam satuan mmHg).
- DiastolicBP: Nilai bawah dari tekanan darah (dalam satuan mmHg).
- BS: Kadar gula darah dalam satuan konsentrasi molar (mmol/L).
- HeartRate: Detak jantung normal pada posisi istirahat (dalam satuan beats per minute).
- RiskLevel: Tingkat resiko terprediksi selama kehamilan dengan pertimbangan atribut sebelumnya attribute.

Mengetahui lebih lanjut mengenai informasi data yang tersedia:
"""

data.info()

"""Memastikan tidak ada data kosong:"""

data.isna().sum()

"""Mengetahui dan menghilangkan data duplikat:"""

data[data.duplicated(keep='first')]

"""Mengubah data 'RiskLevel' menjadi numerik untuk memudahkan pengolahan statistik lebih lanjut dan plot graph."""

data.replace({"high risk":2, "mid risk":1, "low risk":0}, inplace=True)
data.head()

"""Mengetahui statistik data yang tersedia:"""

data.describe()

"""Mengubah data suhu tubuh dari Fahrenheit ke Celcius"""

data['BodyTemp'] = (data['BodyTemp'] - 32) * 5 / 9

"""Memastikan data sudah sesuai"""

data.describe()

"""### Exploratory Data Analysis (EDA)

Bivariate Analysis - Usia terhadap Tingkat Resiko
"""

fig, axes = plt.subplots(nrows=1,ncols=2, figsize=(14,6))

sns.countplot(ax=axes[0], x=data.RiskLevel, palette="Set3")
axes[0].set_title("Total Observations by Risk Level")

sns.boxplot(ax=axes[1], x=data.RiskLevel, y=data.Age, palette="Set3")
axes[1].set_title("Age by Risk Level")

"""Bivariate Analysis - Tekanan Darah terhadap Tingkat Resiko"""

fig, axes = plt.subplots(nrows=1,ncols=2, figsize=(14,6))

sns.histplot(ax=axes[0], x=data.DiastolicBP, color="blue")
axes[0].set_title("Distribution of Lower value of Blood Pressure, mmHg")

sns.histplot(ax=axes[1], x=data.SystolicBP, color="green")
axes[1].set_title("Distribution of Upper value of Blood Pressure, mmHg")

fig, axes = plt.subplots(nrows=1,ncols=2, figsize=(14,6))

sns.boxplot(ax=axes[0], x=data.RiskLevel, y=data.DiastolicBP, palette="Set3")
axes[0].set_title("Lower value of Blood Pressure by Risk Level")

sns.boxplot(ax=axes[1], x=data.RiskLevel, y=data.SystolicBP, palette="Set3")
axes[1].set_title("Upper value of Blood Pressure by Risk Level")

"""Bivariate Analysis - Kadar Gula Darah terhadap Tingkat Resiko"""

sns.boxplot(x=data.RiskLevel, y=data.BS, palette="Set3").set_title("Blood Glucose by Risk Level")

"""Bivariate Analysis - Suhu Tubuh terhadap Tingkat Resiko"""

sns.violinplot(y=data.BodyTemp, x=data.RiskLevel, palette="Set3").set_title("Body Temperature by Risk Level")

"""Bivariate Analysis - Detak Jantung terhadap Tingkat Resiko"""

fig, axes = plt.subplots(nrows=1,ncols=2, figsize=(14,6))

sns.histplot(ax=axes[0], x=data.HeartRate)
axes[0].set_title("Distribution of Heart Rate")

sns.boxplot(ax=axes[1], x=data.RiskLevel, y=data.HeartRate, palette="Set3")
axes[1].set_title("Heart Rate by Risk Level")

"""*Insights:*
- Kehamilan dengan resiko rendah (low risk) adalah yang paling sering dengan lebih dari setengah kasus.
- Wanita yang lebih mudah cenderung memiliki kehamilan dengan resiko rendah (low risk) maupun sedang (mid risk), sementara pada wanita berusia di atas 35 tahun, lebih sering diklasifikasikan sebagai resiko tinggi (high risk).
- Wanita hamil yang memiliki kadar gula darah di atas 8 mmol/L, diklasifikasikan sebagai kehamilan dengan resiko tinggi (high risk).
- Distribusi dari nilai bawah pada tekanan darah (diastol) lebih tersebar, antara 60-100 mmHg, dibandingkan dengan distribusi pada nilai atas (sistol), yang cenderung berkisar pada 120 mmHg.
- Tekanan darah tinggi (both sistol dan diastol) serta suhu tubuh yang tinggi diklasifikasikan sebagai kehamilan dengan resiko tinggi (high risk).
- Detak jantung dari wanita hamil lebih terdistribusi normal dan hanya sedikit berhubungan dengan tingkat resiko.

Menganalisis lebih lanjut karakteristik Systolic BP (tekanan darah sistol) dan
Diastolic BP (tekanan darah diastol) per grup usia.
"""

data.groupby(by="Age").agg({
    "SystolicBP": ["max", "min", "mean", "std"],
    "DiastolicBP": ["max", "min", "mean", "std"],
})

"""Menampilkan grafik rata-rata tekanan darah terhadap usia."""

average_systolicBP_per_age = data.groupby('Age')['SystolicBP'].mean().reset_index()
average_diastolicBP_per_age = data.groupby('Age')['DiastolicBP'].mean().reset_index()

plt.figure(figsize=(12, 6))
ax1 = sns.lineplot(x='Age', y='SystolicBP', label='Systolic BP', data=average_systolicBP_per_age, marker='o', color='red')

ax2 = ax1.twinx()  # Share x-axis with systolic BP plot
sns.lineplot(x='Age', y='DiastolicBP', label='Diastolic BP', data=average_diastolicBP_per_age, marker='s', color='blue', ax=ax2)

plt.title('Average Systolic and Diastolic Blood Pressure per Age Group')
plt.xlabel('Age')
plt.ylabel('Blood Pressure (mmHg)')
plt.xticks(range(data['Age'].min(), data['Age'].max() + 1))
plt.xlabel('Age (years)')
plt.xticks(np.arange(10, 71, 10))  # Set ticks every 10 years
plt.tick_params(axis='x', labelrotation=45, labelsize=12)  # Rotate labels and adjust size
plt.grid(True)
plt.legend(loc='upper left')

plt.show()

"""*Insight*

Berdasarkan usia dan tekanan darah, tekanan darah sangat rendah (baik sistol dan diastol) terekam pada wanita berusia muda, namun tekanan darah normal dan tinggi nampak tidak terlalu berkorelasi dengan usia.

Menganalisis lebih lanjut karakteristik BS (Kadar gula darah), BodyTemp (Suhu tubuh), dan HeartRate (Detak Jantung) per grup usia.
"""

data.groupby(by="Age").agg({
    "BS": ["max", "min", "mean", "std"],
    "BodyTemp": ["max", "min", "mean", "std"],
    "HeartRate": ["max", "min", "mean", "std"],
})

"""Menampilkan grafik BS (Kadar gula darah), BodyTemp (Suhu tubuh), dan HeartRate (Detak Jantung) per grup usia."""

average_BS_per_age = data.groupby('Age')['BS'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x='Age', y='BS', label='Blood Sugar', data=average_BS_per_age, marker='o', color='green')

plt.title('Average Blood Sugar level per Age Group')
plt.xlabel('Age')
plt.ylabel('Blood Sugar Level (mmol/L)')
plt.xticks(range(data['Age'].min(), data['Age'].max() + 1))
plt.xlabel('Age (years)')
plt.xticks(np.arange(10, 71, 10))  # Set ticks every 10 years
plt.tick_params(axis='x', labelrotation=45, labelsize=12)  # Rotate labels and adjust size
plt.grid(True)
plt.legend(loc='upper left')

plt.show()

average_BodyTemp_per_age = data.groupby('Age')['BodyTemp'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x='Age', y='BodyTemp', label='Body Temperature', data=average_BodyTemp_per_age, marker='o', color='blue')

plt.title('Average Body Temperature per Age Group')
plt.xlabel('Age')
plt.ylabel('Body Temperature (Celcius)')
plt.xticks(range(data['Age'].min(), data['Age'].max() + 1))
plt.xlabel('Age (years)')
plt.xticks(np.arange(10, 71, 10))  # Set ticks every 10 years
plt.tick_params(axis='x', labelrotation=45, labelsize=12)  # Rotate labels and adjust size
plt.grid(True)
plt.legend(loc='upper left')

plt.show()

average_HeartRate_per_age = data.groupby('Age')['HeartRate'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x='Age', y='HeartRate', label='Heart Rate', data=average_HeartRate_per_age, marker='o', color='red')

plt.title('Average Heart Rate per Age Group')
plt.xlabel('Age')
plt.ylabel('Heart Rate (Beats per Minute)')
plt.xticks(range(data['Age'].min(), data['Age'].max() + 1))
plt.xlabel('Age (years)')
plt.xticks(np.arange(10, 71, 10))  # Set ticks every 10 years
plt.tick_params(axis='x', labelrotation=45, labelsize=12)  # Rotate labels and adjust size
plt.grid(True)
plt.legend(loc='upper left')

plt.show()

"""*Insights:*
- Kadar gula darah didapati rendah pada wanita hamil berusia muda, sedangkan pada usia 35 tahun ke atas, kadar gula darah mulai meningkat. Hal ini juga menyebabkan klasifikasi resiko tinggi (high risk)
- Suhu tubuh dan usia tidak terlalu berkorelasi.
- Detak jantung dan usia juga tidak terlalu berkorelasi.

Menganalisa tingkat resiko per fitur (Usia, Tekanan darah, Kadar gula darah, Suhu tubuh, dan Detak jantung)
"""

data.groupby(by="RiskLevel").agg({
    "Age": ["max", "min", "mean", "std"],
    "SystolicBP": ["max", "min", "mean", "std"],
    "DiastolicBP": ["max", "min", "mean", "std"],
    "BS": ["max", "min", "mean", "std"],
    "BodyTemp": ["max", "min", "mean", "std"],
    "HeartRate": ["max", "min", "mean", "std"],
})

"""Menampilkan grafik karakteristik terhadap tingkat resiko:"""

num_features = ['Age', 'BS', 'SystolicBP', 'DiastolicBP', 'HeartRate']
risk_level_order = ['0', '1', '2']  # Define the desired order

for col in num_features:
    # Create the catplot with the specified order
    sns.catplot(
        x="RiskLevel",
        y=col,
        kind="bar",
        dodge=False,
        height=4,
        aspect=3,
        data=data,
        palette="Set3",
        order=risk_level_order  # Apply the order to the x-axis
    )
    plt.title("Rata-rata 'RiskLevel' Relatif terhadap - {}".format(col))
    plt.legend('RiskLevel')
    plt.show()  # Show the plot for each feature

"""Mencari korelasi antara usia, tekanan darah, kadar gula darah dan detak jantung"""

correlation = data[['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'HeartRate', 'RiskLevel']].corr(numeric_only=True)
print(correlation)

columns_for_correlation = ['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'HeartRate', 'RiskLevel']
correlation_data = data[columns_for_correlation].corr(numeric_only=True)

plt.figure(figsize=(10, 8))
ax = sns.heatmap(correlation_data, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5, cbar_kws={'label': 'Correlation'})
plt.title('Correlation Matrix of Maternal Health Condition')
plt.show()

columns_for_scatter = ['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'HeartRate', 'RiskLevel']

sns.pairplot(data[columns_for_scatter])
plt.suptitle('Scatter Plot Matrix of Maternal Health Condition', y=1.02)
plt.show()

"""## **Data Preparation**

### Train-Test-Split

Membagi dataset menjadi data latih (train) dan data uji (test) dengan perbandingan 80:20. Ratio ini dianggap cukup karena besar data yang adalah 1014.
"""

from sklearn.model_selection import train_test_split

X = data.drop(["RiskLevel"],axis =1)
y = data["RiskLevel"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

print(f'Total # of sample in whole dataset: {len(X)}')
print(f'Total # of sample in train dataset: {len(X_train)}')
print(f'Total # of sample in test dataset: {len(X_test)}')

"""### Standarisasi

Melakukan standarisasi pada fitur numerik yaitu 'Age', 'SystolicBP', 'DiastolicBP', 'BS', 'HeartRate' dengan menggunakan teknik StandarScaler dari library Scikitlearn. Standarisasi membantu membuat fitur data menjadi bentuk yang lebih mudah diolah oleh algoritma sehingga hasil model akan lebih baik.
"""

from sklearn.preprocessing import StandardScaler

numerical_features = ['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'HeartRate']
scaler = StandardScaler()
scaler.fit(X_train[numerical_features])
X_train[numerical_features] = scaler.transform(X_train.loc[:, numerical_features])
X_train[numerical_features].head()

"""## **Model Development**
Tahap selanjutnya: mengembangkan model machine learning dengan empat algoritma. Kemudian, kita akan mengevaluasi performa masing-masing algoritma dan menentukan algoritma mana yang memberikan hasil prediksi terbaik. Keempat algoritma yang akan kita gunakan, antara lain:

1. Multinominal logistic regression.
2. K-Nearest Neighbor.
3. Random Forest.
4. Decision Tree Classifier.
"""

models = pd.DataFrame(index=['train_mse', 'test_mse'],
                      columns=['LogReg', 'KNN', 'RandomForest', 'DecTree'])

"""### 1. Multinominal Logistic Regression"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error

logistic_regression = LogisticRegression()

logistic_regression.fit(X_train, y_train)

models.loc['train_mse','LogReg'] = mean_squared_error(y_pred = logistic_regression.predict(X_train), y_true=y_train)

"""### 2. K-Nearest Neighbor"""

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

knn = KNeighborsRegressor(n_neighbors=10)
knn.fit(X_train, y_train)

models.loc['train_mse','knn'] = mean_squared_error(y_pred = knn.predict(X_train), y_true=y_train)

"""### 3. Random Forest"""

# Impor library yang dibutuhkan
from sklearn.ensemble import RandomForestRegressor

# buat model prediksi
RF = RandomForestRegressor(n_estimators=50, max_depth=16, random_state=55, n_jobs=-1)
RF.fit(X_train, y_train)

models.loc['train_mse','RandomForest'] = mean_squared_error(y_pred=RF.predict(X_train), y_true=y_train)

"""### 4. Decision Tree Clasifier"""

from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)

models.loc['train_mse','DecTree'] = mean_squared_error(y_pred = decision_tree.predict(X_train), y_true=y_train)

"""### Hyperparameter tuning
Using XGBClassifier
"""

!pip install xgboost
import xgboost as xgb # Import the xgboost module and give it an alias 'xgb'

from sklearn.model_selection import GridSearchCV

xgb_model = xgb.XGBClassifier(n_estimators=50)

# Define hyperparameters to tune
param_grid = {
    'eta': [0.01, 0.05, 0.1, 0.35],
    'max_depth': [2, 4, 7, 9, 12, 17],
    'min_child_weight': [2, 4, 7, 9, 12, 17]
}

# Perform Grid Search Cross Validation to find the best hyperparameters
xgb_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=3)
xgb_search.fit(X_train, y_train)

# Get the best model from Grid Search
xgb_classifier = xgb_search.best_estimator_

# Fit the best model to the training data
xgb_classifier.fit(X_train, y_train)

# Make predictions
xgb_pred = xgb_classifier.predict(X_test)
print("Best parameters found:", xgb_search.best_params_)

"""## **Model Evaluation**"""

from sklearn.metrics import confusion_matrix, classification_report

# Evaluate the model
print('XGBoost Classifier')
print('\n')
print(confusion_matrix(y_test,xgb_pred))
print("\n")
print(classification_report(y_test, xgb_pred))

X_test.loc[:, numerical_features] = scaler.transform(X_test[numerical_features])

# Buat variabel mse yang isinya adalah dataframe nilai mse data train dan test pada masing-masing algoritma
mse = pd.DataFrame(columns=['train', 'test'], index=['LogReg', 'KNN', 'RandomForest', 'DecTree'])

# Buat dictionary untuk setiap algoritma yang digunakan
# FIX: Instantiating the models instead of referencing the classes
model_dict = {'LogReg': LogisticRegression(),
              'KNN': knn,
              'RandomForest': RandomForestRegressor(),
              'DecTree': DecisionTreeClassifier()}

# Hitung Mean Squared Error masing-masing algoritma pada data train dan test
for name, model in model_dict.items():
    model.fit(X_train, y_train)
    mse.loc[name, 'train'] = mean_squared_error(y_true=y_train, y_pred=model.predict(X_train))
    mse.loc[name, 'test'] = mean_squared_error(y_true=y_test, y_pred=model.predict(X_test))

# Panggil mse
mse

fig, ax = plt.subplots()
mse.sort_values(by='test', ascending=False).plot(kind='barh', ax=ax, zorder=4)
ax.grid(zorder=0)

"""*Insight*

Berdasarkan evaluasi di atas, model Random Forest memberikan angka error paling kecil di antara 4 model lainnya, sedangkan model dari Logistic Regression memberikan angka error paling besar.
Karena itu, model Random Forest yang akan dipilih sebagai model terbaik dalam memetakan tingkat resiko kehamilan.

Menguji model
"""

prediksi = X_test.iloc[:1].copy()
pred_dict = {'y_true':y_test[:1]}
for name, model in model_dict.items():
    pred_dict['prediksi_'+name] = model.predict(prediksi).round(1)

pd.DataFrame(pred_dict)